server:
  port: 8050
  servlet:
    session:
      cookie:
        # 避免与本地启动authorizationserver默认的cookie名称：JSESSIONID冲突
        name: UISESSIONCOUPON

---
# OAuth2 Client/Login配置
spring:
  security:
    oauth2:
      client:
        registration:
          # 使用微服务平台 tdf-cloud-oauth-server服务认证
          tdfCloudOAuth2Server:
            client-id: tdfuivue
            client-secret: tdfuivue
            provider: tdfCloudOAuth2Server
            client-name: 太极统一认证
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
          authorizationserver:
            client-id: client-for-server
            client-secret: client-for-server
            provider: authorizationserver
            client-name: 使用自定义授权服务器登录
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            scope: profile
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          tdfCloudOAuth2Server:
            user-name-attribute: "name"
            authorization-uri: ${authorization-cloud-server-url}/oauth/authorize
            token-uri: ${authorization-cloud-server-url}/oauth/token
            user-info-uri: ${authorization-cloud-server-url}/me
            jwk-set-uri: ${authorization-cloud-server-url}/.well-known/jwks.json
          authorizationserver:
            authorization-uri: http://localhost:9999/oauth/authorize
            token-uri: http://localhost:9999/oauth/token
            user-info-uri: http://localhost:9999/me
            user-name-attribute: "name"
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json
authorization-cloud-server-url: http://192.168.99.77:9998

logging:
  level:
    org.springframework.web: Debug
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: INFO
